name: Test go package

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Mod
      run: go mod tidy && go mod download
    
    - name: Vet
      run: go vet ./...
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
